# Generated by Django 2.1.5 on 2019-11-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191124_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='user',
        ),
        migrations.DeleteModel(
            name='host',
        ),
    ]
