# Generated by Django 2.1.5 on 2019-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20191124_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='checkin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='checkout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
