# Generated by Django 2.1.5 on 2019-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20191125_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='checkin',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='checkout',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
